name: get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
version: 1.4.1
homepage: https://github.com/jonataslaw/get_cli

environment:
  sdk: ">=2.7.0 <3.0.0"

executables:
  get: get

dependencies:
  ansicolor: ^1.0.2
  archive: ^2.0.13
  cli_dialog: ^0.3.3
  cli_menu: ^0.2.2
  dart_style: ">=1.0.10 <2.0.0"
  http: ^0.12.2
  intl: ^0.16.1
  json_ast: ^1.0.5
  meta: ^1.2.3
  path: ^1.7.0
  process_run: ^0.11.2+1
  recase: ^3.0.0
  version: ^1.2.0
  yaml: ^2.2.1
  io: ^0.3.4

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
